# Generated by Django 4.2.2 on 2023-09-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='product_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
